version: "3"
services:
  api-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - homelike-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - homelike-network
    volumes:
      - mongo-data:/data/db
networks:
  homelike-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local